### ISSUE TITLE
Supplemental Documents

### ISSUE THREAD

**Issue by brian-lee-intelledox** [docusign/docusign-csharp-client#119]
Are supplemental documents supported with the latest version of the SDK?  I can't seem to find reference to the properties includeInDownload, display, and signerMustAcknowledge on the Document object when looking through the source code.  I also can't find reference to the view tab in TemplateTabs.cs.

If they aren't currently supported in the SDK do you have a date in which they will be?  Can you share the steps required for me to add them if necessary?

Thanks,

Brian

**Comment by mmallis87** [comment]
If you're talking about the fields that are part of the Document object that is return by the getDocument(s) API then that will be available in SDKs this month. ETA is March 15th.

General note: after a new version of the API is out, we update the SDKs and make them available. So there will be always some time where the SDKs are a bit behind the API. We are improving our process and technology so that the lead time is reduced each time. In case you need an API feature that is not in the SDK yet and can't wait for it to be shipped, then the workaround is to do the raw HTTP call yourself using an HTTP lib of your choice. For .NET we recommend RestSharp, as this is what is used in this SDK.

**Comment by brian-lee-intelledox** [comment]
Hi Majid.

I'm speaking specifically about the properties that are set on the Document object when creating an envelope as well as the "View" tab that is used in conjunction with the Approve tabs ("To use the View and Approve tabs for supplemental documents, the document display property must be set to modal or download.").  Are those going to be included in the SDK drop on March 15th?

Is the new Swagger definition available?  I'm fine with rebuilding the SKD using Swagger CodeGen.

Thanks so much!

![supplementaldocuments](https://cloud.githubusercontent.com/assets/26240393/23672602/358e86e6-033d-11e7-95e1-c19d52d0416e.png)

**Comment by mmallis87** [comment]
Yes these properties will be in the upcoming version of the SDK, so stay tuned!

Unfortunately we still aren't ready to release our API spec files. We are actually working on that process and targeting next quarter for GA.

**Comment by mmallis87** [comment]
@brian-lee-intelledox Here is the pre-release branch, feel free to give it a try and let us know in case you find anything wrong: https://github.com/docusign/docusign-csharp-client/tree/2.1.0

**Comment by brian-lee-intelledox** [comment]
@mmallis87 ... you're a life saver.  Supplemental Documents works perfectly.  We were able to code against the pre-release SDK and we will swap it out for the production version when it is available in mid-march.

thank you!

**Comment by mmallis87** [comment]
I'm glad to hear that. My plan is to push a release before the weekend. So stay tumed!
