### ISSUE TITLE
Production Base URL / 404

### ISSUE THREAD

**Issue by Greatsamps** [docusign/docusign-csharp-client#142]
When running on production Docusign require you to use a different BaseURL, for example, one of our accounts is na3.docusign.net.

You can get this base URL from the loginInfo request, but this includes much more than just the base:

https://na3.docusign.net/restapi/v2/accounts/1234

When using this baseURL as a constructor for ApiClient(), this is causing subsequent calls to fail with a 404 error as they are adding v2/accounts/1234 onto the path again.

We have gotten around this by hardcoding the base url, which is clearly far from ideal.

**Comment by LarryKlugerDS** [comment]
Thank you for the problem report.
For new applications that use OAuth authentication, the [OAuth::getUserInfo](https://developers.docusign.com/esign-rest-api/guides/authentication/user-info-endpoints) method must be used instead of the old Authentication::login call. That call must only be used with legacy authentication.

The getUserInfo call returns just the platform information for the base url. Eg, `https://na3.docusign.net`. You must then add on the `/restapi` segment before setting the SDK. 

The code examples [eg-03-csharp-auth-code-grant-core](https://github.com/docusign/eg-03-csharp-auth-code-grant-core) and [eg-01-csharp-jwt-core](https://github.com/docusign/eg-01-csharp-jwt-core) show how to do this.
