### ISSUE TITLE
No feedback from rest API when SMS Authentication is not available on account

### ISSUE THREAD

**Issue by markjritchie** [docusign/docusign-csharp-client#16]
I'm currently working on adding SMS authentication to the ,NET client, it was very quick to implement however I was not aware that I had successfully implemented and have lost almost a whole day trying to discover what is wrong.

It turns out that the SMS authentication is only available on Buisiness accounts, however the REST API documentation does not mention this, the response from the API does not return an error or any feedback to say that the feature is not available.

Please consider adding the useful nugget of information to the docs and while I can understand DocuSign not wanting to incur the costs of sending lots of SMS it would be good if a mock SMS authentication page was displayed to show that the request was correct.

**Comment by mikebz** [comment]
Mark,
I am very sorry you spent so much time on this.  It could be that you have found a bug in our system where we are not giving you an error code if the feature is not enabled.  

There is a debate on whether or not our REST API documentation should mention should mention specifics of the plans.  I think we can argue both ways on that one, but it's true that the API definitely should give you a clear message if you have sent a request which can not be fulfilled.

Do you mind giving us a little more information here?
1) URL where you are sending the request
2) the JSON of the request (maybe excluding the PDF bytes if you are not using the templates)
3) when you have attempted to make those requests
4) the account numbers that you have tried to make the request again

Thank you and our sincere apologies.

**Comment by markjritchie** [comment]
Hi Mike,

I can post the anonymised rest traces here if you want or if you give me your email address I can send you as much info as possible

Regards
Mark

**Comment by mikebz** [comment]
If you can post them here. We want to make sure that if there is a resolution it gets indexed by search engines.

On Apr 16, 2015 12:24 AM, markjritchie <notifications@github.com> wrote:

Hi Mike,

I can post the anonymised rest traces here if you want or if you give me your email address I can send you as much info as possible

Regards
Mark

**Comment by markjritchie** [comment]
Here's the rest trace with the sensitive parts removed:

OST: https://demo.docusign.net/restapi/v2/accounts/996652/envelopes?api_password=true

Headers:
X-DocuSign-Authentication:<DocuSignCredentials><Username>foo@foo.de</Username><Password>Password=</Password><IntegratorKey>AReallyGoodKey</IntegratorKey></DocuSignCredentials>
Content-Type:multipart/form-data; boundary=00000000-0000-0000-0000-000000000000
Host:demo.docusign.net
Content-Length:65170
Expect:100-continue

Request Stream:

--00000000-0000-0000-0000-000000000000
Content-Type: application/json
Content-Disposition: form-data

{"emailBlurb":"Test Blurb","emailSubject":"Test subject","status":"sent","recipients":{"signers":[{"email":"foo@foo.de","name":"Signer 1: 963963273377441","recipientId":"1","requireIdLookup":"true","smsAuthentication":{"senderProvidedNumbers":["+4911111111"]},"idCheckConfigurationName":"Sms Auth $","emailNotification":{"emailBody":"Signer 1 Body: 963963273377441 ","emailSubject":"Signer 1 Subject: 963963273377441","supportedLanguage":"en"}},{"email":"foo@bar.com","name":"Signer 2: 963963273387376","recipientId":"2","emailNotification":{"emailBody":"Signer 2 Body: 963963273387376","emailSubject":"Signer 2 Subject: 963963273387376","supportedLanguage":"de"}}]},"documents":[{"documentId":"1","name":"Test Contract.pdf"}]}

--00000000-0000-0000-0000-000000000000
Content-Type: application/pdf
Content-Disposition: file; filename="Test Contract.pdf"; documentId=1

[file bits go here]

--00000000-0000-0000-0000-000000000000--


Response:
{
  "envelopeId": "a4e23d0a-4df0-426e-b583-d6cd5caa1c25",
  "uri": "/envelopes/a4e23d0a-4df0-426e-b583-d6cd5caa1c25",
  "statusDateTime": "2015-04-16T14:45:44.2730000Z",
  "status": "sent"
}


POST: https://demo.docusign.net/restapi/v2/accounts/996652/envelopes/a4e23d0a-4df0-426e-b583-d6cd5caa1c25/views/sender.json?api_password=true

Headers:
Accept:application/json
Content-Type:application/json
X-DocuSign-Authentication:<DocuSignCredentials><Username>foo@bar.com</Username><Password>9Haasdas7aaaadaGTmVHo=</Password><IntegratorKey>AReallyGoodKey</IntegratorKey></DocuSignCredentials>
Host:demo.docusign.net
Content-Length:16
Expect:100-continue

Request Stream:
{"returnUrl":""}


Response:
{
  "url": "https://demo.docusign.net/Member/StartInSession.aspx?StartConsole=1&t=1cc3e1b9-c3e6-4140-ae81-941b5f783c38&DocuEnvelope=a4e23d0a-4df0-426e-b583-d6cd5caa1c25&send=1"
}

**Comment by mikebz** [comment]
Hi Mark!

Quick update on this issue.  I have engaged out product team on this.  A couple of things I have verified:
1) SMS is enabled on demo accounts
2) SMS is supported in other countries (we have had folks confirm that they work in UK at least).

It might be best for you to contact support because this might be a bit of a debugging session.  Do you have an Account Manager?

One of the things to try here is to see if you can send the envelope with SMS auth through the regular user interface.

Thanks and sorry it wasn't working immediately.

**Comment by zsoltkollarits** [comment]
Hi Mike,

Apparently we have a very similar on our side, could you please help us?

We implemented an app that's using DocuSign .Net Client, here is the scenario it does .:
1.	It creates an empty (draft) Envelope and adds few documents (by url) to it.
2.	Then the rest of the Envelope is configured in c# webbrowser by the user: our app is asking for the Envelope's SenderView url (calling its GetSenderView method) and loading the url into the browser.
3.	At this point our customers can add some Recipients, Tabs, and can configure the email subject and body. 
4.	When finished with configuration, they click on the “Send” button of your SenderView (top-right corner) and a new "draft" Envelope appaers on your webpage.

The whole procedure works perfectly fine (we were keep on testing this in the past few months), but a problem happens on DocuSign SenderView if the user switches the authentication type to SMS (Austrian phone number) for one of the recipients. In this case clicking on the “Send” button simply doesn’t do anything. Nothing happens at all, DocuSign SenderVIew page behaves like we haven’t clicked on anything. Nothing is loaded, no envelope is created at DocuSign webpage.

I think this issue is rather a .Net Client/REST API problem, therefore we’d really like to know why the “Send” button stops working if the user tries to use SMS authentication. Obviously we cannot look behind DocuSign's “Send” button, the SenderView is totally out of our control, hence we have no chance to continue debugging. Please note we’re still using a Demo account, not sure if it matters or not.

Could you please check if the combination of
- having a DocuSign demo account
- using the API's SenderView (Send button) to create an envelope
- switching to SMS authentication and providing an Austrian phone number
is working or not?

Thanks in advanced for all the responses!
Zsolt

**Comment by mikebz** [comment]
Hi Zsolt.

Thank you for choosing DocuSign and giving our client library a try.  We appreciate it.  From your description it doesn’t seem like you are doing anything incorrectly.  This could be an issue with SMS providers in Austria.  I am going to ask around and see if someone knows about this as a known limitation or a bug.

Stay tuned.

-mb

--
Mike Borozdin
Sr. Director of Engineering || @mikebz || mikeb@docusign.com<mailto:mikeb@docusign.com>

On Dec 7, 2015, at 2:08 AM, zsoltkollarits <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Mike,

Apparently we have a very similar on our side, could you please help us?

We implemented an app that's using DocuSign .Net Client, here is the scenario it does .:
1. It creates an empty (draft) Envelope and adds few documents (by url) to it.
2. Then the rest of the Envelope is configured in c# webbrowser by the user: our app is asking for the Envelope's SenderView url (calling its GetSenderView method) and loading the url into the browser.
3. At this point our customers can add some Recipients, Tabs, and can configure the email subject and body.
4. When finished with configuration, they click on the “Send” button of your SenderView (top-right corner) and a new "draft" Envelope appaers on your webpage.

The whole procedure works perfectly fine (we were keep on testing this in the past few months), but a problem happens on DocuSign SenderView if the user switches the authentication type to SMS (Austrian phone number) for one of the recipients. In this case clicking on the “Send” button simply doesn’t do anything. Nothing happens at all, DocuSign SenderVIew page behaves like we haven’t clicked on anything. Nothing is loaded, no envelope is created at DocuSign webpage.

I think this issue is rather a .Net Client/REST API problem, therefore we’d really like to know why the “Send” button stops working if the user tries to use SMS authentication. Obviously we cannot look behind DocuSign's “Send” button, the SenderView is totally out of our control, hence we have no chance to continue debugging. Please note we’re still using a Demo account, not sure if it matters or not.

Could you please check if the combination of

  *   having a DocuSign demo account
  *   using the API's SenderView (Send button) to create an envelope
  *   switching to SMS authentication and providing an Austrian phone number is working or not?

Thanks in advanced for all the responses!
Zsolt

**Comment by zsoltkollarits** [comment]
Hi Mike,

Since my last post here, I continued invetigating the problem and have a feeling that something is wrong with your webpage, its behavior is totally dependent upon the browser I'm using:
- This moment my IE 11 browser doesn't open demo.docusign.net at all.
- My Chrome opens the page and a new document can be uploaded without any problems. However I cannot change authentication type on a certain page, please have a look at the following scenarios for better understanding:

Scenario 1:
Enter demo.docusign.net into your Chrome and login -> click on new document -> apply template -> add recipient -> set SMS authentication with phone number -> click on Next -> you see your document preview now and can set some signature positions -> click on Send. 

This scenario is working, apparently I could create a document with SMS authentication request.

Scenario 2:
Enter demo.docusign.net into your Chrome and login -> click on new document -> apply template -> add recipient -> click on Next -> you see your document preview now and can set some signature positions -> click on Edit recipients -> click on "..." button in order to set SMS authentication -> nothing appears in my Chrome, therefore I cannot switch to SMS authentication.

This scenario is not working, this is the way how we try to upload a document in our app. 

From the facts above I would say something is wrong with your webpage, recipients - also the type of authentication - cannot be configured properly on the page where document preview is visible. Configuring the authentication type on the first page - where you see the recipient list - of upload procedure is working in Chrome and also in our app, but could not do the same at document preview page so far.

It's very likely your webpage - especially the new style of your page - has some issues and there is not much to fix in our app. I cannot reach demo.docusign.net from IE 11 (neither compatibility view works) at all, in Chrome your "Edit Recipients" dialog is not working as "..." button does not react. Our apps webbrowser  - which theoretically uses IE 11 too - allows you to click on the "..." button and configure eberything but then Send button click is simply ignored.

As a summary: I think our app, our API calls, and also your .Net Client are all working fine, the problem is rather with the SenderView we show in our C# Webbrowser. That page is doesn't seem to be stable as some buttons might not functioning, therefore we cannot click on "Send" when SMS authentication is set.

Thanks for looking into this issue!

Regards,
Zsolt

**Comment by InbarGazit** [comment]
@zsoltkollarits our "front end" web pages have a "classic' and a "new" experience. I'm not sure which one you're using, is there a way you can post a screenshot here?

**Comment by zsoltkollarits** [comment]
I'm always using the new experience of your webpage as our clients - they are going to use our app - also prefer the new style. Here is the screenshot of my Chrome browser:

![screenshot](https://cloud.githubusercontent.com/assets/16188054/11692439/bd597c24-9e9f-11e5-8458-9fe8f63c566e.png)

Quick explanation what our C# app does:
1. Gets a path to a document and creates a new Envelope for that document. Nothing special so far.
2. Gets the SenderView for that Envelope and loads it into our C# webbrowser component.
3. The rest of the configuration can be done in that particular webbrowser view, after clicking on "Send" the Envelope appears at your webpage as a draft.

Problem: If we click on "Edit Recipients" under "Other actions" and switch to SMS authentication, the "Send" button of your webpage simply stops working, all of our clicks are ignored, the Envelope cannot be sent out.

Thanks in advance!
Zsolt

**Comment by InbarGazit** [comment]
Thank you, we will work with our web team to address this issue. Just to be completely certain this is a UI issue - can you try to, for testing purposes only, switch to the "classic" UI and see if this works ok in there?

**Comment by mikebz** [comment]
It looks like there is indeed a bug.  Are you working with someone in account management? We will need to find an internal bug and have someone repro and fix it.

-mb

--
Mike Borozdin
Sr. Director of Engineering || @mikebz || mikeb@docusign.com<mailto:mikeb@docusign.com>

On Dec 9, 2015, at 8:44 AM, zsoltkollarits <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Mike,

Since my last post here, I continued invetigating the problem and have a feeling that something is wrong with your webpage, its behavior is totally dependent upon the browser I'm using:

  *   This moment my IE 11 browser doesn't open demo.docusign.net<http://demo.docusign.net> at all.
  *   My Chrome opens the page and a new document can be uploaded without any problems. However I cannot change authentication type on a certain page, please have a look at the following scenarios for better understanding:

Scenario 1:
Enter demo.docusign.net<http://demo.docusign.net> into your Chrome and login -> click on new document -> apply template -> add recipient -> set SMS authentication with phone number -> click on Next -> you see your document preview now and can set some signature positions -> click on Send.

This scenario is working, apparently I could create a document with SMS authentication request.

Scenario 2:
Enter demo.docusign.net<http://demo.docusign.net> into your Chrome and login -> click on new document -> apply template -> add recipient -> click on Next -> you see your document preview now and can set some signature positions -> click on Edit recipients -> click on "..." button in order to set SMS authentication -> nothing appears in my Chrome, therefore I cannot switch to SMS authentication.

This scenario is not working, this is the way how we try to upload a document in our app.

From the facts above I would say something is wrong with your webpage, recipients - also the type of authentication - cannot be configured properly on the page where document preview is visible. Configuring the authentication type on the first page - where you see the recipient list - of upload procedure is working in Chrome and also in our app, but could not do the same at document preview page so far.

It's very likely your webpage - especially the new style of your page - has some issues and there is not much to fix in our app. I cannot reach demo.docusign.net<http://demo.docusign.net> from IE 11 (neither compatibility view works) at all, in Chrome your "Edit Recipients" dialog is not working as "..." button does not react. Our apps webbrowser - which theoretically uses IE 11 too - allows you to click on the "..." button and configure eberything but then Send button click is simply ignored.

As a summary: I think our app, our API calls, and also your .Net Client are all working fine, the problem is rather with the SenderView we show in our C# Webbrowser. That page is doesn't seem to be stable as some buttons might not functioning, therefore we cannot click on "Send" when SMS authentication is set.

Thanks for looking into this issue!

Regards,
Zsolt

**Comment by LarryKlugerDS** [comment]
Thank you for using DocuSign. I'm closing out old issues that haven't been updated recently. Please re-open if this is still an issue. Thank you.
