### ISSUE TITLE
Updated Usage example returns 400 Bad Request on oauth/token call

### ISSUE THREAD

**Issue by jeffhee** [docusign/docusign-csharp-client#187]
Hello,
The Usage example on the ReadMe works just fine against the Sandbox environment. 

However, using the same code but with my production userid, and OAuth base path of "account.docusign.com" returns a 400 Bad Request error.

It is reproducible 100% of the time.

Please assist, thank you!

**Comment by RajRele** [comment]
@jeffhee You may be missing the consent part - this is a one time activity before you can move forward with JWT authentication. 
Just update your integrator key and Redirect Uri below and give consent when prompted... and try again...
https://account.docusign.com/oauth/auth?response_type=code&scope=signature%20impersonation&client_id=**$YourIntegratorKey**&redirect_uri=**$YourRedirectUri**

Please See - https://developers.docusign.com/esign-rest-api/guides/authentication/oauth2-jsonwebtoken

**Comment by jeffhee** [comment]
Hi there,
Consent was already granted. To confirm, I tried it again and was sent directly to the redirect url, bypassing the authorization screen.

**Comment by RajRele** [comment]
Hi @jeffhee  Confirm what version you are using, we recommend NuGet v2.2.0 or latest GitHub release v2.2.0.

If your using the latest csharp client you may get more information on the response, by debugging at this line. https://github.com/docusign/docusign-csharp-client/blob/12ee722bca4321eea7b9f192ee127b36296cdab5/sdk/src/DocuSign.eSign/Client/ApiClient.cs#L826

Just to confirm you are using your host for production as "https://www.docusign.net/restapi"
and oauthbasepath as "account.docusign.com"

You can give more details on your issue here https://support.docusign.com/en/createCase

Thanks

**Comment by jeffhee** [comment]
Hello,
First of all, thank you for your prompt responses. :)

Just pulled latest, now running under GitHub release v2.2.0 and experiencing the same error result on production only. Using the correct production host of https://www.docusign.net/restapi and oauth base path of account.docusign.com, the CallApi line is returning a "BadRequest" error.

I've already created a ticket, #04233413. There hasn't been any responses from the CS team since June 25th. 

Thank you!

**Comment by thallesrv** [comment]
any answer?

**Comment by LarryKlugerDS** [comment]
Hi @thallesrv , this issue was closed almost two years ago.

If you're having a problem using the C# SDK, the best way to get help is to open a request on StackOverflow, with tag `docusignapi`. 

If you feel the SDK itself has a bug, you can raise a new issue here. Thank you, Larry
