### ISSUE TITLE
How to consume refresh token

### ISSUE THREAD

**Issue by arthur-conde** [docusign/docusign-csharp-client#210]
How do I use the OAuth.OAuthToken.refresh_token to get a new token?

I don't see any methods using grant_type=refresh_token.

**Comment by LarryKlugerDS** [comment]
The DocuSign oauth authentication server implements the refresh token exchange operation in a standard way. So the oauth library that you're using should enable you to exchange a valid refresh token for a new set of {access_token, refresh_token, and expires_in} data.

For example, if you use the DotNetOpenAuth library, [here](https://www.google.co.il/search?q=dotnetopenauth+refresh+token&oq=www.dotnetopenauth+refresh) is some info on using the refresh token.

**Comment by arthur-conde** [comment]
Oh I can't use this library to do it. Alright, thanks.

**Comment by LarryKlugerDS** [comment]
Sorry, I should have summarized better: 

The SDK does not implement the refresh token exchange operation and it is not on the roadmap for the SDK.

The DocuSign SDKs' goal is that they don't implement any part of the oauth authorization code grant flow since there are many libraries available for that flow. 

Some of the SDKs do currently implement parts of the flow but implementation support for the oauth authorization code grant flow will only be decreased, not increased.

In contrast, the SDKs support the OAuth JWT flow since library support for that flow is not always available from 3rd party libraries.
