### ISSUE TITLE
RestClient Execute Counts Twice Against Rate Limit

### ISSUE THREAD

**Issue by brbeaird** [docusign/docusign-csharp-client#211]
Is it expected that most calls (example: get templates) would generate two hits against the hourly DocuSign rate limit? I debugged it all the way down to RestClient.Execute, and that's the point where it does the callout and DocuSign logs 2 calls.

I've honestly never looked this closely at it until now, but it's annoying that this essentially doubles our usage. Once a year, we need to send out a pretty large chunk of documents, and this double-counting slows us down quite a bit.

**Comment by LarryKlugerDS** [comment]
Please re-open the issue if you have further questions on it.

**Comment by LarryKlugerDS** [comment]
Hi, 

One of my colleagues has noted that there could be a bug whereby the SDK makes one API call to DocuSign, but the DocuSIgn platform (by mistake) increments the calls made in the last hour counter by 2 instead of the expected 1.

If this is what you think is happening, please reply with the API call that you made where there might be an issue. 

In all cases, only one actual API call is made by the SDK per call from your app.

**Comment by brbeaird** [comment]
You were correct - I totally missed a spot where my code was calling it twice. Sorry about that! Thanks.

**Comment by LarryKlugerDS** [comment]
Glad to help! Thank you for using DocuSign.
Regards,
Larry
