### ISSUE TITLE
default PurgeState for requested Envelope

### ISSUE THREAD

**Issue by tehnetaholic** [docusign/docusign-csharp-client#78]
```c#
            EnvelopeSummary envelopeSummary = envelopesApi.CreateEnvelope(accountID, envDef);
            var envelope = envelopesApi.GetEnvelope(accountID, envelopeSummary.EnvelopeId);
            envelope.Status = "sent";
            envelope.PurgeState = "";
            envelopesApi.Update(accountID, envelope.EnvelopeId, envelope);
```

PurgeState property had "unpurged" value. I had to clear PurgeState property, since otherwise I was getting

> "errorCode": "INVALID_REQUEST_PARAMETER",
> 
>   "message": "The request contained at least one invalid parameter. Value for 'purgeState' must be 'documents_queued' or 'documents_and_metadata_queued'."

**Comment by Ergin008** [comment]
You can only purge envelopes that are in the `"completed"` state.  These are the requirements listed in the REST API docs for the Purge Documents Call:

`This provides the ability to initiate a request to place envelope documents and envelope metadata in a purge queue so that this information is removed from the DocuSign system. The request can only be used for completed envelopes that are not marked as authoritative copy. The requesting user must have permission to purge documents and must be the sender (the requesting user can act as the sender using Send On Behalf Of).`

For an envelope to move to the completed state all of the recipients need to sign and/or complete their actions (except for CC recipients).  If instead you want to stop the transaction from completing then you can void the envelope by making the **Void Envelope** API call.

**Comment by tehnetaholic** [comment]
@Ergin008 
Thank you for the reply.
I didn't desire to purge an envelope, that's the problem.
What I wanted to archieve is:
- Create an Envelope with "created" status
- Update its status to "sent"

The thing is, if I remove `envelope.PurgeState = "";` then your API decides that I want to purge an Envelope, and throws an error, about incorrect value, since the passed value is "unpurged"

But all I wanted to do is to update a status of an envelope, that I've just received.
It's contrinuitive, don't you think?

**Comment by Ergin008** [comment]
@tehnetaholic  Got it, thanks for that explanation.  

I've been testing this and just figured it out.  The API call to **Send a Draft Envelope** only has one required parameter, which is the `status` param.  The `purgeState` property should not be included in this request, and when you do a full `GET` on the envelope like you are doing to get the `EnvelopeID` then the purgeState is automatically returned and becomes part of your request to send the envelope.  

To get around that you can simply do the following, which is better anyways since it requires one less DocuSign API call:

	EnvelopeSummary envelopeSummary = envelopesApi.CreateEnvelope(accountId, envDef);

	// store the resulting envelope ID that is generated
	string EnvelopeId = envelopeSummary.EnvelopeId;

	// instead of retrieving the entire envelope definition just set the Status property
	Envelope envelope = new Envelope();
	envelope.Status = "sent";
	
	// now your update call will be a success
	envelopesApi.Update(accountId, EnvelopeId, envelope);

**Comment by tehnetaholic** [comment]
@Ergin008 Thank you
Yes, this works, and requires less calls
