### ISSUE TITLE
Inconsistent usage of baseUrl

### ISSUE THREAD

**Issue by sbraswell** [docusign/docusign-csharp-client#95]
Our assumption is that the baseUrl passed into the `ApiClient` constructor for production accounts needs to point to the DS data center that the account is hosted on (i.e. NA1, NA2, EU, etc.). This baseUrl is discovered by calling the `AuthenticationApi.Login()` method and examining the value of `LoginAccount.BaseUrl`. Due to inconsistent handling of the baseUrl in the library we are having to format our own baseUrl to pass to the `ApiClient` constructor.

The format returned by `AuthenticationApi.Login()` is as follows:

    `https://demo.docusign.net/restapi/v2/accounts/{accountId}`

However line 2315 in EnvelopesApi is setting the path to `var path_ = "/v2/accounts/{accountId}/envelopes";` which assumes the value passed into the `ApiClient` constructor is something of the form:

    `https://demo.docusign.net/restapi`

Would it be possible to make the baseUrl accepted in the constructor of `ApiClient` the same as that which is returned by the call to `AuthenticationApi.Login()`?

Is our assumption about the baseUrl to pass into the `ApiClient` constructor correct? It needs to point to the correct data center for the account?

Thank you for your help!

**Comment by brbeaird** [comment]
I've run into the same issue and ended up just hard-coding my data center in to the ApiClient call. A change like this would be nice.

**Comment by LarryKlugerDS** [comment]
Thank you for raising the issue.

For Legacy Authentication, it is unfortunately the case that the "login" method returns the longer url as you've noted.  We can't change this behavior since it would be a breaking change.

The good news is that the DocuSIgn [OAuth: Userinfo method](https://docs.docusign.com/esign/guide/authentication/userinfo.html) `base_uri` (server name) field for each account is the just the first part of the basePath. Eg `https://na1.docusign.net` 

So you still need to add `/restapi` to it when using the REST API. But that's a lot better than the necessity to split the string returned by the older method.

Adding restapi to the `base_uri` field value is appropriate since it enables the value to be independent of any specific API supported by the platform.

Note that the OAuth UserInfo method is only for OAuth authentication.

@brbeaird be careful--hardcoding the basePath is a brittle solution since your code will not work with all accounts (different accounts are on different systems).
